### PR TITLE
Add corewar app package

### PR DESCRIPTION
**Pull request by dougajmcdonald**
Adds the new `corewar-app` package and removes the old UI.

Fixes issues with dependencies and versions which I saw locally.

Confirmed running from a state with no `node_modules` > lerna boostrap > npm start

### CODE REVIEW

**Comment by gareththegeek** [comment]
I can resolve the problem by prefixing all the scripts with `npx`.  I'll do that and push the changes.

**Comment by gareththegeek** [comment]
I'm not sure that `lerna` is installing `corewar-app` dependencies.  I didn't get a `node_modules` folder for `corewar-app` until I ran `npm run build` inside the `corewar-app` folder.  Actually it looks like all corewar-app dependencies are going into the mono-repo root `node_modules` folder - not sure if that is desireable or not.

**Comment by gareththegeek** [comment]
Also a lot of dev dependencies are back in root `package.json` which I removed in my PR

**Comment by gareththegeek** [comment]
So it works as it is but loads of dependencies are duplicated in child packages and at root and if you remove them it breaks but I don't know why.  We also need to have all the packages listed as dependencies of the root package.json or it breaks - also don't know why.  Basically I don't know how the config got the way it did and I don't really know why any of it works ??

**Comment by gareththegeek** [comment]
Ok, I think `lerna` is ignoring dev dependencies at the package level altogether.  Also, I removed all the dev dependencies from `packages/corewar` and now linting fails for `corewar-app` - why wouldn't that happen?

**Comment by gareththegeek** [comment]
Gotta stop now, famliy are looking at me angrily.  @dougajmcdonald  Could you try removing all dev dependencies from `packages/corewar` and `npm run clean`.  Manually delete top `node_modules` and then `npm run bootstrap` and `npm run lint` ?

**Comment by gareththegeek** [comment]
I'm finding it is now linting the build folder

**Comment by dougajmcdonald** [comment]
> I get the following from corewar-app `npm run build`: did you install `react-scripts` globally? Could it be a dev dependency?
> 
> > 'react-scripts' is not recognized as an internal or external command

react-scripts is part of create-react-app which I think I have globally, could put it in the dev deps?

**Comment by dougajmcdonald** [comment]
> I'm not sure that `lerna` is installing `corewar-app` dependencies. I didn't get a `node_modules` folder for `corewar-app` until I ran `npm run build` inside the `corewar-app` folder. Actually it looks like all corewar-app dependencies are going into the mono-repo root `node_modules` folder - not sure if that is desireable or not.

I wasn't sure what the expected behaviour was here. For me I get a node_modules folder in corewar-app but it only contains a .cache folder with a couple of things in it. I thought it was meant to hoist the deps to avoid duplication at lower levels?

**Comment by dougajmcdonald** [comment]
> Also a lot of dev dependencies are back in root `package.json` which I removed in my PR

I can put those back (or take them out! I forgot which one it is!)

**Comment by dougajmcdonald** [comment]
> I'm not sure that `lerna` is installing `corewar-app` dependencies. I didn't get a `node_modules` folder for `corewar-app` until I ran `npm run build` inside the `corewar-app` folder. Actually it looks like all corewar-app dependencies are going into the mono-repo root `node_modules` folder - not sure if that is desireable or not.

This is the behaviour I saw when I first got the lernafied stuff, since I got it working without needing an npm i at child level, i assumed that it wasn't needed / supposed to work that way!

You can put an explicit lerna exec npm install step in the npm bootstrap command but I didn't think we were meant to need to do that!

**Comment by dougajmcdonald** [comment]
> Gotta stop now, famliy are looking at me angrily. @dougajmcdonald Could you try removing all dev dependencies from `packages/corewar/package.json` and `npm run clean`. Manually delete top `node_modules` and then `npm run bootstrap` and `npm run lint` ?

This worked for me. Now I think about it I think the npm run bootstrap is the one I used rather than lerna on it's own cos the bootstrap stuff...I think? Linting also worked.

image

**Comment by dougajmcdonald** [comment]
I'm doing it! :shipit:

**Pull request merged**
